# @package model.size
size: large
variants:
  rnn:
    hidden_size: 1536
  transformer:
    embedding_dim: 320
    num_layers: 4
    num_heads: 8
    dropout_prob: 0.1
    widening_factor: 4
  cnn1d:
    embedding_dim: 256
    hidden_channels: 896
    num_layers: 5
    dropout: 0.1
  nca1d:
    channel_size: 128
    hidden_size: 512
    num_steps: 96
    num_kernels: 2
    kernel_size: 3
    cell_dropout_rate: 0.1
    input_embedding_dim: 64
  tiny_recursive:
    hidden_size: 544
    H_layers: 4
    L_layers: 4
    H_cycles: 2
    L_cycles: 2
    halt_max_steps: 2
  hrm:
    hidden_size: 432
    H_layers: 3
    L_layers: 3
    H_cycles: 2
    L_cycles: 2
    halt_max_steps: 2
    expansion: 1.9
    num_heads: 8
    pos_encodings: rope
    halt_exploration_prob: 0.0
    forward_dtype: float32
    mlp_t: false
  tape_rnn:
    hidden_size: 1280
    memory_cell_size: 384
    memory_size: 120
    n_tapes: 1
    mlp_layers_size: [640, 640]
    inner_core: lstm
    input_window: 1
  stack_rnn:
    hidden_size: 1344
    stack_cell_size: 400
    stack_size: 128
    n_stacks: 1
    inner_core: lstm
    input_window: 1
