# @package model.size
size: large
variants:
  rnn:
    hidden_size: 1536
  rnn_ar:
    hidden_size: 768
    teacher_forcing: true
  transformer:
    embedding_dim: 448
    num_layers: 4
    num_heads: 8
    dropout_prob: 0.1
    widening_factor: 4
  transformer_ar:
    embedding_dim: 320
    num_layers: 4
    num_heads: 8
    dropout_prob: 0.1
    widening_factor: 4
    teacher_forcing: true
  cnn1d:
    embedding_dim: 256
    hidden_channels: 896
    num_layers: 5
    dropout: 0.1
  nca1d:
    channel_size: 384
    hidden_size: 6144
    num_steps: 96
    num_kernels: 2
    kernel_size: 3
    cell_dropout_rate: 0.1
    input_embedding_dim: 128
  tiny_recursive:
    name: recursive_reasoning.trm@TinyRecursiveReasoningModel_ACTV1
    loss:
      name: losses@ACTLossHead
      loss_type: stablemax_cross_entropy
    halt_exploration_prob: 0.1
    halt_max_steps: 16
    H_cycles: 3
    L_cycles: 6
    H_layers: 0
    L_layers: 2
    hidden_size: 608
    num_heads: 8  # min(2, hidden_size // 64)
    expansion: 4
    puzzle_emb_ndim: ${.hidden_size}
    pos_encodings: rope
    forward_dtype: bfloat16
    mlp_t: false  # use mlp on L instead of transformer
    puzzle_emb_len: 16
    no_ACT_continue: true  # No continue ACT loss, rely on halt sigmoid
  hrm:
    name: recursive_reasoning.hrm@HierarchicalReasoningModel_ACTV1
    loss:
      name: losses@ACTLossHead
      loss_type: stablemax_cross_entropy
    halt_exploration_prob: 0.1
    halt_max_steps: 16
    H_cycles: 2
    L_cycles: 2
    H_layers: 4
    L_layers: 4
    hidden_size: 320
    num_heads: 8  # min(2, hidden_size // 64)
    expansion: 4
    puzzle_emb_ndim: ${.hidden_size}
    pos_encodings: rope
    forward_dtype: bfloat16
    mlp_t: false
  transformer_act:
    name: recursive_reasoning.transformers_baseline@Model_ACTV2
    loss:
      name: losses@ACTLossHead
      loss_type: stablemax_cross_entropy
    halt_exploration_prob: 0.1
    halt_max_steps: 16
    H_cycles: 1  # kept for compatibility
    H_layers: 6
    hidden_size: 384
    num_heads: 8
    expansion: 2.5
    puzzle_emb_ndim: ${.hidden_size}
    pos_encodings: rope
    forward_dtype: bfloat16
