# @package model.size
size: medium
variants:
  rnn:
    hidden_size: 512
  transformer:
    embedding_dim: 160
    num_layers: 2
    num_heads: 5
    dropout_prob: 0.1
    widening_factor: 2
  cnn1d:
    embedding_dim: 160
    hidden_channels: 320
    num_layers: 4
    dropout: 0.1
  nca1d:
    channel_size: 192
    hidden_size: 1536
    num_steps: 64
    num_kernels: 2
    kernel_size: 3
    cell_dropout_rate: 0.1
    input_embedding_dim: 96
  tiny_recursive:
    hidden_size: 224
    H_layers: 2
    L_layers: 2
    H_cycles: 1
    L_cycles: 1
    halt_max_steps: 1
  hrm:
    hidden_size: 168
    H_layers: 2
    L_layers: 2
    H_cycles: 1
    L_cycles: 1
    halt_max_steps: 1
    expansion: 1.6
    num_heads: 4
    pos_encodings: rope
    halt_exploration_prob: 0.0
    forward_dtype: float32
    mlp_t: false
  tape_rnn:
    hidden_size: 416
    memory_cell_size: 104
    memory_size: 40
    n_tapes: 1
    mlp_layers_size: [208, 208]
    inner_core: lstm
    input_window: 1
  stack_rnn:
    hidden_size: 448
    stack_cell_size: 112
    stack_size: 42
    n_stacks: 1
    inner_core: lstm
    input_window: 1
